---
roles:
  - name: buluma.bootstrap
  - name: buluma.buildtools
  - name: buluma.epel
  - name: robertdebock.microsoft_repository_keys
  - name: buluma.python_pip
collections:
  - name: community.general
